version: "2"
services:
  web:
    build: .
    volumes:
     - .:/app/
     - /app/node_modules
    ports:
     - "3000:3000"
    links:
     - mongo
    environment:
     NODE_ENV: 'development'
  mongo:
   image: mongo
   ports:
     - "27017:27017"
   volumes:
    - .:/mnt/
   volumes_from:
     - mongodata
  mongodata:
    image: tianon/true
    volumes:
      - /data/db
  nginx:
    image: nginx:alpine
    ports:
     - 80:80
    links:
     - web
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
